package com.aallam.openai.client.internal.api

/**
 * Object to handle API paths.
 */
internal object ApiPath {
    const val Translation = "audio/translations"
    const val Transcription = "audio/transcriptions"
    const val Speech = "audio/speech"
    const val ChatCompletions = "chat/completions"
    const val Completions = "completions"
    const val Conversations = "conversations"
    const val Edits = "edits"
    const val Embeddings = "embeddings"
    const val Files = "files"
    const val FineTunes = "fine-tunes"
    const val ImagesGeneration = "images/generations"
    const val ImagesEdits = "images/edits"
    const val ImagesVariants = "images/variations"
    const val Models = "models"
    const val Moderations = "moderations"
    const val FineTuningJobs = "fine_tuning/jobs"
    const val Assistants = "assistants"
    const val Threads = "threads"
    const val VectorStores = "vector_stores"
    const val Batches = "batches"
    const val Responses = "responses"
    const val Videos = "videos"
    const val Evals = "evals"
    const val SafetyCases = "safety/cases"
    const val SafetyAlerts = "safety/alerts"
    const val Uploads = "uploads"
    const val WebhookEndpoints = "webhook_endpoints"
    const val WebhookEventTypes = "webhook_event_types"
    const val Containers = "containers"
    const val Skills = "skills"
    const val LiveSessions = "live/sessions"
    const val AdminProjects = "organization/projects"
    const val Projects = "projects"
    const val AdminUsers = "organization/users"
    const val AdminInvites = "organization/invites"
    const val AdminApiKeys = "organization/admin_api_keys"
    const val Realtime = "realtime"
    const val RealtimeClientSecrets = "realtime/client_secrets"
    const val RealtimeSessions = "realtime/sessions"
    const val RealtimeTranscriptionSessions = "realtime/transcription_sessions"
    const val RealtimeCalls = "realtime/calls"
    const val AdminGroups = "organization/groups"
    const val AdminCertificates = "organization/certificates"
    const val AdminRoles = "organization/roles"
    const val AdminAuditLogs = "organization/audit_logs"
    const val AdminSpendAlerts = "organization/spend_alerts"
    const val AdminSpendLimit = "organization/spend_limit"
    const val AdminDataRetention = "organization/data_retention"
    const val AdminExternalStorage = "organization/external_storage"
    const val AdminUsage = "organization/usage"
    const val AdminCosts = "organization/costs"
    const val Agents = "agents"
    const val AgentSessions = "agents/sessions"
    const val AgentEnvironments = "agents/environments"
    const val EnvironmentTemplates = "agents/environments/templates"
    const val Vaults = "vaults"
    const val ChatKitSessions = "chatkit/sessions"
    const val ChatKitThreads = "chatkit/threads"
}
